### ISSUE TITLE
Wow this server is popular

### ISSUE THREAD

**Issue by CountryChamp** [Pugmatt/BedrockConnect#338] opened 2022-09-16 07:07 UTC
### What happened?

So when I connect using the DNS it keeps saying wow server is popular. So I was like weird I was working fine last night let me try a different DNS so I tried the 2nd public one for US and its taking me straight to the servers. I've been sitting here for about an hour and half trying to see if its my fault restarting my console power cycling and all. I'm on a Xbox series s and its just being weird. I have tried all of the bedrock connect dnses and they are either telling me unable to connect or wow this server is too popular or its just flat saying unable to connect. I have a 72mb download and a 29mp upload and idk what wrong. Could you share some insite as to why this is happening?

### Expected Behaviour?

To immediately connect to the server list I have on the DNS server.

### Steps to reproduce.

1. Open mc
2. Click server
3. Wow this server is popular or unable to connect to world.

### Screenshots/Videos

![IMG_20220916_020545626](https://user-images.githubusercontent.com/113666413/190577432-b9189716-ee16-412f-a9f8-f36c3e37c6d9.jpg)
![IMG_20220916_020526494](https://user-images.githubusercontent.com/113666413/190577454-84dfd69f-436d-4bab-b287-e38af31cf09f.jpg)

### Minecraft Bedrock Version

1.19.22

### Console

Xbox Series S

### Additional Context

I've gone through all of the DNS servers and I have them typed in correctly. It worked last night and now its just stopped IG.

**Comment by ShaunSteven** [comment] 2022-09-17 15:21
We are experiencing the same issue, this was working last night around 9pm EDT but today we are getting the same error message.

**Comment by WombleWoo7547** [comment] 2022-09-17 15:23
Same here.

**Comment by ShaunSteven** [comment] 2022-09-17 15:24
Looks like another reboot and redownload of the Switch software allowed us to connect.

**Comment by WombleWoo7547** [comment] 2022-09-17 15:31
@ShaunSteven thats odd I tried that on xbox one twice and no success. Like I said I'm self-hosting

**Comment by vzabawski** [comment] 2022-09-18 17:47
I’m experiencing same problem with main server on Nintendo Switch. Eventually it works, but sometimes I have to restart the game a couple of times and wait, wait a lot.

**Comment by Pugmatt** [comment] 2022-09-18 18:26
Not totally sure what is causing this, especially since for some it's happening on all the DNSs not just the main one. I believe it's a Minecraft bug, as the servers themselves are not actually full.

Microsoft doesn't seem to have much documentation on what this error means, but from what it looks like based off some bug reports it means either the host or server itself is on an unstable connection. Considering a lot of people are still able to connect to BedrockConnect, I'm thinking it might be an issue with the Minecraft client being far away from the server.

I would recommend anyone with this issue doing the following:

- Use a self-hosted instance of BedrockConnect locally on your network like WombleWoo did (https://github.com/Pugmatt/BedrockConnect#hosting-your-own-serverlist-server)
- If you can't host a self-hosted one, you can try changing your secondary DNS to something different. (https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#the-internet-on-my-console-is-not-working-at-all-now) It could also just be experiencing issues by being on the Google DNS for the secondary, and you could try the other ones. Or find one that is local in your country.

I'll continue to investigate the issue, but considering it's happening for a lot of people on all instances, I'm thining this a Minecraft bug or an issue caused by being far away from the servers kind of issue.

**Comment by vzabawski** [comment] 2022-09-19 07:49
>  believe it's a Minecraft bug, as the servers themselves are not actually full.

Totally agree. For me, the whole process looks this way:
1. I launch Mineraft.
2. It starts, loads main screen. "Minecraft Store" button is inactive (usually, it takes ~10 seconds for it to become active), player's model on in the right corner of the screen is loading.
3. Minecraft automatically logs into Microsoft account, then usually player's model starts loading too and "Store" button becomes active. At least, it was that way before the problem occurred. However, last several days I'm getting to the next step.
4. "Minecraft Store" button is still inactive, player's model is still loading. In that state, Minecraft can stay for several minutes, then it either logs in, or doesn't, and I have to restart it.

Sometimes "Minecraft Store" button becomes active, but I can't still open servers list. That's when I get "Wow this server is popular", but for me more frequent behavior is eternal loading.

**Comment by Pugmatt** [comment] 2022-09-20 06:58
> > believe it's a Minecraft bug, as the servers themselves are not actually full.
> 
> Totally agree. For me, the whole process looks this way:
> 
> 1. I launch Mineraft.
> 2. It starts, loads main screen. "Minecraft Store" button is inactive (usually, it takes ~10 seconds for it to become active), player's model on in the right corner of the screen is loading.
> 3. Minecraft automatically logs into Microsoft account, then usually player's model starts loading too and "Store" button becomes active. At least, it was that way before the problem occurred. However, last several days I'm getting to the next step.
> 4. "Minecraft Store" button is still inactive, player's model is still loading. In that state, Minecraft can stay for several minutes, then it either logs in, or doesn't, and I have to restart it.
> 
> Sometimes "Minecraft Store" button becomes active, but I can't still open servers list. That's when I get "Wow this server is popular", but for me more frequent behavior is eternal loading.
> 
> @Pugmatt if you still don't have a Mojang Jira account, and you need to create a bug, let me know. I would be more than happy to do that, especially if I have more technical details.

Sure, if you're able to submit a bug report for this feel free, thank you. I haven't been able to replicate the error with success on my end yet, so you would probably have more details than me.

I've had the issue on the Switch version of the game taking a while to log in and load the store, or not log in at all upon first start for a couple of years now, always seems to be buggy. (Even with no custom DNS in place) Haven't gotten the "Wow this server is popular" error yet though.

**Comment by vzabawski** [comment] 2022-09-20 08:28
Okay. I'll try to reproduce this bug with regular DNS and see if it appears.

**Comment by WombleWoo7547** [comment] 2022-10-19 06:58
I think this is closed, as I had for a few weeks, self-hosted for that time, but DNS is back up 100%, so I use that for simplicity.
I cannot close this, but I believe it is fixed

**Closed** 2022-10-19 08:11 UTC

**Comment by vzabawski** [comment] 2022-10-19 08:30
Same for me.

**Comment by mrtumnus** [comment] 2023-02-13 15:04
I'm getting this error now after setting up my own BedrockConnect server.

Client is Windows 10 Bedrock edition Minecraft v1.19.60
Server is a Debian LXC container, just running the java jar from the shell with a custom server list

Is there any debug output I can capture from the BedrockConnect server?  It doesn't seem to be throwing any error when the client tries to connect.

**Comment by mrtumnus** [comment] 2023-02-13 15:09
I did a wireshark trace, and it looks like the server is responding with "No Free Incoming Connections"
![image](https://user-images.githubusercontent.com/1738198/218495205-837b8c94-185b-4d80-80cf-7aaf9ba22dce.png)

**Comment by mrtumnus** [comment] 2023-02-13 15:21
Nevermind - figured it out.  I'm running BedrockConnect on the same container that my Minecraft servers are running on.  Port 19132 was already being listened on by one of the servers (even though they are specified for other ports!  Minecraft server bug, I think).  I shut down those servers and can now connect to the serverlist.
