### ISSUE TITLE
Bedrock Connect LazyBirb Needs to update to Minecraft Version 1.21

### ISSUE THREAD

**Issue by B4DM4N12Z** [Pugmatt/BedrockConnect#502] opened 2024-06-13 22:46 UTC
### What happened?

LazyBirb's Bedrock Connect server needs to be updated to the latest Minecraft Version 1.21 
(Tricky Trails) as it is unusable at the moment. 

I'm not sure everyone has this problem or if it has been fixed but it is showing me it is not updated to Minecraft Version 1.21.

I hope this gets updated. Thank you for reading.

### Expected Behaviour?

I expected for it to be updated

### Minecraft Bedrock Version

1.21

### Console

Xbox one

### Additional Context

Has to be updated to the latest update 1.21 (Tricky Trails)

**Comment by GERDominik165** [comment] 2024-06-14 11:36
Issue Description
The Bedrock Connect server by LazyBirb needs to be updated to the latest Minecraft version 1.21 (Tricky Trails) as it is currently unusable.

What Happened?
When attempting to join the server list, it always shows that the host has not been updated. This occurs in the Bedrock edition of Minecraft.

Expected Behavior
I expected the server to be updated to the latest version 1.21 so that it becomes usable again.

Steps to Reproduce
Start Minecraft Bedrock Edition version 1.21.
Attempt to join the BedrockConnect server list.
An error message appears stating that the host has not been updated.
Platforms Where the Issue Occurs
Xbox One
PlayStation 4
PlayStation 5
Nintendo Switch
Windows
Linux
Screenshots/Videos
None provided.

Minecraft Bedrock Version
1.21

Additional Context
The server needs to be updated to the latest update 1.21 (Tricky Trails) to become usable again. Additionally, the BedrockConnect-1.0-SNAPSHOT.jar should finally be updated for the latest version because the current version, which supposedly supports 1.21.0, does not actually support 1.21.0.

**Comment by B4DM4N12Z** [comment] 2024-06-14 12:27
Thank you for clarifying this issue 👍🏽

**Comment by GERDominik165** [comment] 2024-06-14 12:40
> Vielen Dank für die Klärung dieses Problems 👍🏽



> Thank you for clarifying this issue 👍🏽

no problem , i have the same issue on selfhost , so that why i repost your issue its a little bit the same problem "outdated for 1.21.0 clients"

**Comment by B4DM4N12Z** [comment] 2024-06-14 13:06
Do you play Xbox or Roblox?

**Comment by B4DM4N12Z** [comment] 2024-06-14 13:08
Do you play Xbox or Roblox?

**Comment by LazyBirb** [comment] 2024-06-19 08:16
Problem resolved, you may close the issue

**Closed** 2024-06-19 16:31 UTC
