### ISSUE TITLE
PS5 to Java servers?

### ISSUE THREAD

**Issue by ShaKKDiseL** [Pugmatt/BedrockConnect#141] opened 2021-01-08 03:38 UTC
I'm having a hard time going to a great server by the name of Gridcraft. Below is their server address

play.gridmc.io

I've used GeyserMC as well as MP trial ed. I can't seem to log on. Please help me.

**Comment by kmpoppe** [comment] 2021-01-08 04:44
AFAIK, the PS5 run the Bedrock Version of Minecraft. That means you will NOT be able to play on a Java Server. This is not a fault in the BedrockConnect project, rather a design by Mojang and Microsoft. More here: https://help.minecraft.net/hc/en-us/articles/360034753992-Different-Minecraft-Editions

**Comment by Pugmatt** [comment] 2021-01-08 04:53
> I'm having a hard time going to a great server by the name of Gridcraft. Below is their server address
> 
> play.gridmc.io
> 
> I've used GeyserMC as well as MP trial ed. I can't seem to log on. Please help me.

Could you expand on what part isn't letting you log on? Are you having trouble getting into the BedrockConnect serverlist, or are you able to make it into the BedrockConnect serverlist, and the issue occurs when trying to join Gridcraft from there? 

If you're able to get on the BedrockConnect serverlist and the issue is occuring when joining Gridcraft from there, that's out of BedrockConnect's hands, and I would recommend asking the guys over at Geyser.

> AFAIK, the PS5 runs the Bedrock Version of Minecraft. That means you will NOT be able to play on a Java Server. This is not a fault in the BedrockConnect project, rather by design from the developers Mojang and Microsoft. More here: https://help.minecraft.net/hc/en-us/articles/360034753992-Different-Minecraft-Editions

GeyserMC is a tool that allows the Bedrock version of Minecraft to connect to Java edition servers. So it should be possible join in this case.

**Comment by ShaKKDiseL** [comment] 2021-01-08 07:36
> > I'm having a hard time going to a great server by the name of Gridcraft. Below is their server address
> > play.gridmc.io
> > I've used GeyserMC as well as MP trial ed. I can't seem to log on. Please help me.
> 
> Could you expand on what part isn't letting you log on? Are you having trouble getting into the BedrockConnect serverlist, or are you able to make it into the BedrockConnect serverlist, and the issue occurs when trying to join the GeyserMC proxy to join Gridcraft?
> 
> If you're able to get on the BedrockConnect serverlist and the issue is occuring when joining the GeyserMC proxy to connect to Gridcraft from there, that's out of BedrockConnect's hands, and I would recommend asking the guys over at Geyser.
> 
> > AFAIK, the PS5 runs the Bedrock Version of Minecraft. That means you will NOT be able to play on a Java Server. This is not a fault in the BedrockConnect project, rather by design from the developers Mojang and Microsoft. More here: https://help.minecraft.net/hc/en-us/articles/360034753992-Different-Minecraft-Editions
> 
> GeyserMC is a tool that allows the Bedrock version of Minecraft to connect to Java edition servers. So it should be possible join in this case if they have an instance of GeyserMC running.

Thank you for the advice. I will try to contact GeyserMC.

**Comment by kmpoppe** [comment] 2021-03-24 22:19
I think this issue can be closed as not being relevant for BC?

**Comment by ShaKKDiseL** [comment] 2021-03-25 11:52
Yes you can close

**Closed** 2021-03-25 15:11 UTC

**Comment by Heath123** [comment] 2022-01-28 21:22
> I'm having a hard time going to a great server by the name of Gridcraft. Below is their server address
> 
> play.gridmc.io
> 
> I've used GeyserMC as well as MP trial ed. I can't seem to log on. Please help me.

See https://www.geyserconnect.net/
