### ISSUE TITLE
Not working with 1.18.10 anymore on Nintendo Switch

### ISSUE THREAD

**Issue by kmpoppe** [Pugmatt/BedrockConnect#272] opened 2022-02-08 18:12 UTC
### What happened?

After updating the Nintendo Switch client to 1.18.10, I can connect to the server list but the redirection to the servers from the list doesn't work anymore.

The Switch displays Generating world but from what I see in the debug screen of my (1.18.11) Ubuntu server, the connect never gets through.

Could this be in conjuntion to @Camotoy's remark that something was wrong with the protocol?

Kai

### Excepted Behaviour?

See before.

### Minecraft Bedrock Version

1.18.10

**Comment by CrafterPika** [comment] 2022-02-08 18:44
Same issue here.

**Comment by kmpoppe** [comment] 2022-02-08 18:50
Unsure if good or bad news, using the Android version of the game (albeit not really needing the server list there because you can add your own servers) connecting through the server list works without issues.

I have the feeling the Switch version might have taken on a bug ... Or it's intentional by Nintendo -.-

**Comment by CrafterPika** [comment] 2022-02-08 18:53
> Or it's intentional by Nintendo -.-
Wouldn't surprise me, as I am someone who quite often runs Atmosphere on my switch.

Usually I would go around trying to mess around with [PrismarineJS's Libary](https://github.com/PrismarineJS/bedrock-protocol) trying to replicate it there but it hasn't been updated yet.

**Comment by kmpoppe** [comment] 2022-02-08 18:56
I might add that the Featured Servers also don't work when trying to connect through the server list, so it's at least not an sercer-ident Filter or something...

**Comment by CrafterPika** [comment] 2022-02-08 19:05
Don't forget their either [direct ips](https://github.com/Pugmatt/BedrockConnect/blob/master/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/BedrockConnect.java#L173) or handles via [InetAddress.getByName](https://github.com/Pugmatt/BedrockConnect/blob/master/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java#L69)

**Comment by CrafterPika** [comment] 2022-02-08 19:11
anyway let me update [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere) and try to fire up [Noexes](https://github.com/mdbell/Noexes) Debugger to see whats going on.

**Comment by kmpoppe** [comment] 2022-02-08 19:14
> anyway let me update [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere) and try to fire up [Noexes](https://github.com/mdbell/Noexes) Debugger to see whats going on.

Gladly :)

**Comment by CrafterPika** [comment] 2022-02-08 20:13
~1 hour later i still have struggle using it,
I honestly haven't it since 3 years, and there hasn't been a new release since 2018... aswell that the Java Software needs Java10 doesn't make anything easy.... 

i am gonna look into a temporary solution for this later...

**Comment by Ultrameow** [comment] 2022-02-08 22:17
Same issue, glad this was caught early on, so people can look into it :)
This is very troublesome to me as i am a helper and builder for an mc server, hope this gets figured out soon, thank you for your time.

**Comment by Pugmatt** [comment] 2022-02-08 23:38
Pretty sure featured servers like the Hive use transfer packets in some cases, such as when switching to other regioned servers with the region picker located in their hub. Upon choosing a different region, the same issue seemed to happen similar to choosing a server in the BedrockConnect serverlist, glitched out and didn't work.

Knowing this I'm doubting this bug is intentional, since it's affecting their official servers.

Also want to add, although a bit unrelated to BedrockConnect: For anyone that urgently needs to get on a server today and already knows how to host your own DNS server, you can technically change the records on your hosted DNS server to the IP of the server you're trying to join instead of the BedrockConnect instance.

**Comment by dturner34** [comment] 2022-02-09 02:44
Half of the users on my server just updated to 1.18.10, lost access and are fussing at me over this.

**Comment by catalinacat** [comment] 2022-02-09 04:17
Came here to see if I was alone having this issue. Glad I'm not! Hopefully we'll be able to play soon

**Comment by CrafterPika** [comment] 2022-02-09 08:28
> Knowing this I'm doubting this bug is intentional, since it's affecting their official servers.

yea it’s more likely Mojang forgot to transfer the fix to the Nintendo switch, it’s probably gonna get fixed soon since it’s quite game breaking for those who play on featured servers, it also would’ve been very weird from Nintendo (Since Mojang would not out of nothing brother with it) to force them to blockade the transfer packet, especially knowing that things like [switch lan play](http://lan-play.com/games-switch) have been now around 4 years now, and there has never been an attempt to blockade it. But again it would not suprise me if Nintendo actually did something.

**Comment by kmpoppe** [comment] 2022-02-09 08:53
Let's for now presume that my initial suspicion against Nintendo doesn't hold true and I'm just a bit overly critical these days given the happenings in the Mario Maker-community.

I can't find any info in the Mojang Bugtracker for this problem, so I wonder if Mojang as even realized this.

**Comment by dturner34** [comment] 2022-02-09 15:41
Seems like this project is critical for everyone running on console, I'm hearing of a lot of people sitting on their hands waiting for this fix.  Is there any way we could have tested this before 1.18.10 was rolled out?

**Comment by kmpoppe** [comment] 2022-02-09 16:14
I don't know of any way to install a Beta Version of the game on a console, so testing would've been limited to versions where you could join the Beta program, namely Android (iOS?) and PC - which do not really need BedrockConnect.

*Insert rant about console providers reducing game functionality for money making reasons here*

**Comment by CrafterPika** [comment] 2022-02-09 16:15
> (iOS?)
iOS has an TestFlight here https://testflight.apple.com/join/qC1ZnReJ

**Comment by AndrwGamerYT** [comment] 2022-02-09 17:19
I have the same problem. I hope solutions can be found :))

**Comment by dturner34** [comment] 2022-02-09 18:09
It looks like you can opt-in to beta test on xbox
https://help.minecraft.net/hc/en-us/articles/360040841471-How-Do-I-Join-and-Leave-the-Minecraft-Beta-
Are we already testing this way? It seems like the client app is similar enough to catch most things.

If the issue is exclusive to Nintendo,  it might be worth sending them threatening emails until they let someone from here in on a beta program.

**Comment by CrafterPika** [comment] 2022-02-09 18:13
> If the issue is exclusive to Nintendo

This seems to be the case, unless @Pugmatt tested if it also happens on Xbox.

**Comment by Camotoy** [comment] 2022-02-09 18:19
I have not heard of any issues from Xbox. This bug is likely a one-time occurrence (possibly something that couldn't quite be fixed on time as all other platforms fixed their issue from the beta). There's no reason having the beta in our hands specifically on Switch would solve the issue.

**Comment by MattHardwick34** [comment] 2022-02-09 18:37
I have at least one user on my server reporting this issue on Xbox, obviously nothing to do with the server but he still complained to me about it. Nintendo users also complaining.

**Comment by Pugmatt** [comment] 2022-02-09 20:00
Don't have an Xbox on hand currently to test on Xbox, but by the sound of the reply above me, it can be possible. Seems to primarily be a Nintendo Switch issue though, I suppose mostly since Xbox users technically also have the LAN proxy bypass that they can also use instead of the DNS/BedrockConnect bypass.

Whether we had a beta test version or not, we were already technically aware a couple of days ago the issue with the transfer packets (https://github.com/Pugmatt/BedrockConnect/pull/271). There really isn't anything we could do then, and nothing we can really do now, as it's an issue with the game client itself that is currently causing this.

Since this is affecting featured servers, it will most likely be fixed by Mojang soon, just will need to be patient. I understand this is affecting many server owners, but BedrockConnect's hands are as tied as the servers that need it right now unfortunately.

Best thing right now is to submit a bug report to the Bedrock Edition bug tracker to make sure Mojang is aware of the bug, while trying to avoid mentioning BedrockConnect in the report as it's not their problem, but do mention the issues on the featured servers as that very much is their problem. Tried to create an account on the bug tracker but it doesn't seem to be letting new accounts at this time? Unless I'm just looking in the wrong spot. (https://bugs.mojang.com/secure/Signup!default.jspa) If anyone does have a bug tracker account, would be great if we could get a bug report out containing something like the following:

```
The recent 1.18.10 version of the Nintendo Switch version appears to have brought a bug in relation to servers that use the transfer functionality to transfer players to another server, which can be found in some of the servers listed in "Featured Servers". On the Hive, using the region selector in the hub attempts to switch servers, but ultimately fails with no error and goes back to the Minecraft main menu. This same behavior can be found on Pixel Paradise when selecting a game mode.

Steps to Reproduce:

  1. Enter the Hive or Pixel Paradise from the "Servers" tab in the main menu
  2. If on Hive: Use the "Region Selector" located in the hub and choose a region
     If on Pixel Paradise: Use the compass in the hub, click "Games", and choose any gamemode.

Observed Results:
The game changes screen and shows the "Generating World" box, but then suddenly closes and brings you back to the Minecraft main menu. This happens every time.

Expected Results:
Connect to the server being directed to by the server

Screenshots/Videos:
Video: https://streamable.com/6s4d5r
```

Could also maybe mention it as the "Transfer packet" specifically, but probably not a good idea?

That's as much we can do I think, for now. I will tinker with some ideas I have when I have more free time, but hopefully by that time the bug will already be fixed by Mojang.

**Comment by vzabawski** [comment] 2022-02-09 21:03
Hi @Pugmatt. I've created a bug report on Mojang Jira.
https://bugs.mojang.com/browse/MCPE-152265
And btw, thanks for your server, it really helps me to chill in the evening with Switch. :)

**Comment by Pugmatt** [comment] 2022-02-09 21:17
> Hi @Pugmatt. I've created a bug report on Mojang Jira. https://bugs.mojang.com/browse/MCPE-152265 And btw, thanks for your server, it really helps me to chill in the evening with Switch. :)

Thanks for posting that, much appreciated.  Hopefully that will get Mojang's attention.

**Comment by vzabawski** [comment] 2022-02-10 08:40
I've found another ticket in Mojang Jira related to this issue. Not sure which one will be closed as "duplicate", so here's a link to another one, just in case.
https://bugs.mojang.com/browse/MCPE-152238

**Comment by Pugmatt** [comment] 2022-02-10 08:43
Oof, was really hoping no one would mention BedrockConnect in the bug reports. I still think the original bug report you posted will probably hold up better, and not be marked as duplicate. We'll see.

**Comment by kmpoppe** [comment] 2022-02-10 08:58
> Oof, was really hoping no one would mention BedrockConnect in the bug reports. 

Are we sure, that Mojang are not already are fully aware of BedrockConnect being a thing? Alas, my guess is they don't care and are more driven by Nintendo to not allow adding of own servers...

**Comment by CrafterPika** [comment] 2022-02-10 09:04
> Are we sure, that Mojang are not already are fully aware of BedrockConnect being a thing?

They are, some literally posted an issue about bedrock connect once lol https://bugs.mojang.com/browse/MCPE-102132?attachmentOrder=desc

**Comment by Pugmatt** [comment] 2022-02-10 09:04
> > Oof, was really hoping no one would mention BedrockConnect in the bug reports.
> 
> Are we sure, that Mojang are not already are fully aware of BedrockConnect being a thing? Alas, my guess is they don't care and are more driven by Nintendo to not allow adding of own servers...

Actually, I just did a search in the bug trackers and people have technically mentioned BedrockConnect before in the past. And the staff always just say "We don't support that, so we can't help" and nothing more. I'm sure they're well aware of the project at this point, I just don't like taking chances haha. 

Plus in terms of this issue, I don't want Mojang thinking this transfer packet issue is just affecting BedrockConnect, something they don't support. But hopefully the first bug report we posted will stop that confusion from happening.

**Comment by CrafterPika** [comment] 2022-02-10 09:25
And slp has been around since [August 2018](https://github.com/spacemeowx2/switch-lan-play/graphs/contributors), it would‘ve been a strange move from Nintendo to break the one, but not the other especially the one that get‘s around Nintendo‘s services.

**Comment by CrafterPika** [comment] 2022-02-10 09:39
i do understand the distrust in Nintendo, they can such *insert insult here*, but upper mentioned point just makes it an odd move.

**Comment by vzabawski** [comment] 2022-02-10 10:27
> > Are we sure, that Mojang are not already are fully aware of BedrockConnect being a thing?
> 
> They are, some literally posted an issue about bedrock connect once lol https://bugs.mojang.com/browse/MCPE-102132

I like the wording in the ticket. :D
>if u did know whats BedrockConnect is ...........go search on google

**Comment by evanpacini** [comment] 2022-02-10 22:15
Hey, same issue over here since the Switch 1.18.10 update... Glad to see this is being discussed. Great project btw!

**Comment by Raxcental** [comment] 2022-02-11 17:49
https://feedback.minecraft.net/hc/en-us/articles/4424805981069

**Comment by kmpoppe** [comment] 2022-02-11 17:51
The wording sounds like it. Great news!

**Comment by CrafterPika** [comment] 2022-02-11 17:53
Haven't got the update yet, also the issue on bugs.mojang.com hasn't been resolved yet https://bugs.mojang.com/browse/MCPE-152265, but from looking Mojang recognised the issue as other duplicates have been redirect to vzabawski one.

**Comment by CrafterPika** [comment] 2022-02-11 17:54
** Now I got it

**Comment by kmpoppe** [comment] 2022-02-11 17:55
Closed as not a BC Issue. Thanks everyone for the awesome support!

**Closed** 2022-02-11 17:55 UTC

**Comment by CrafterPika** [comment] 2022-02-11 17:57
Just tested 1.18.11, the issues is fixed 🎉

**Comment by gbernabe** [comment] 2022-02-11 18:46
I tested 1.18.11 too and work's fine now

**Comment by evanpacini** [comment] 2022-02-12 10:24
Yess! Thanks for the support everyone!
