### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by G9-Dev** [Pugmatt/BedrockConnect#196] opened 2021-06-08 16:42 UTC
Hello 'n sorry
Yes it doesnt work with 1.17
Please update it quickly i need it and sorry again

**Comment by Pugmatt** [comment] 2021-06-08 18:25
It is already updated to 1.17, and working on the version. What platform and version are you on? And what error?

**Comment by so-nakashima** [comment] 2021-06-08 18:33
I faced the same problem.
My console is Switch and the version is 1.17.0.
The error is "Unable to Connect to World".

I could connect to my server at about 11:00 GMT, but now I have the problem.

**Comment by TerrienDJV5** [comment] 2021-06-08 18:35
I'm also facing the same problem on Switch

**Comment by Pugmatt** [comment] 2021-06-08 18:47
I performed some tests on a Switch just now, and I appear to be getting "Unable to Connect to World" even without the DNS in place. It seems to be broken even in a default state, but could just be something weird on my end. Can anyone else confirm this on theirs?

**Comment by so-nakashima** [comment] 2021-06-08 18:57
Thanks a lot. 
I also got "Unable to Connect to World" when the DNS setting is automatic (default).

**Comment by G9-Dev** [comment] 2021-06-08 19:14
I also got "Unable to Connect to World" when the DNS setting is automatic (default).
Fun fact : before there was 6 servers, now they are 7 of the

**Comment by PaulW** [comment] 2021-06-08 20:32
I've raised this as an issue on Mojangs bug tracker here

https://bugs.mojang.com/browse/MCPE-130282

Can confirm this is an issue with Switch only it seems. This isn't the first time this particular issue has happened following an update either. But hey, at least this time it's not completely locking the switch up!

**Comment by corpsepain** [comment] 2021-06-09 01:14
literally just joined Github to say it is a same issue on PS4

**Comment by Nystrata** [comment] 2021-06-09 03:35
Yeah, this affects the actual official Featured servers as well

A work around that's been working for me is to start or continue a singleplayer world, and then Save & Quit to the main menu
The servers in the Servers tab should work after that

**Comment by maki-taki** [comment] 2021-06-09 14:51
Why this is happening is the 1.17 update bugging out the switch. Read the update docs.
Pain

**Comment by spikehidden** [comment] 2021-06-09 17:48
There's a workaround:

1. Enable local mode via the Y-button on the title screen.
2. Reenable online mode and wait until you logged into your Microsoft Account
3. Switch to the Server-Tab and choose any Server you like.
4. Wait until there's a number at Ping.
5. Connect and it should work now.

**Comment by jbenammi** [comment] 2021-06-10 02:54
> Yeah, this affects the actual official Featured servers as well
> 
> A work around that's been working for me is to start or continue a singleplayer world and then Save & Quit to the main menu
> The servers in the Servers tab should work after that
> 
Confirmed this work around is good.

**Comment by Pugmatt** [comment] 2021-06-10 04:06
> There's a workaround:
> 
> 1. Enable local mode via the Y-button on the title screen.
> 2. Reenable online mode and wait until you logged into your Microsoft Account
> 3. Switch to the Server-Tab and choose any Server you like.
> 4. Wait until there's a number at Ping.
> 5. Connect and it should work now.

Thanks for posting this. I'll add it to the troubleshooting page until Nintendo/Mojang releases a robust fix for it.

**Comment by G9-Dev** [comment] 2021-06-13 08:59
idk if it's linked, but my Microsoft account doesn't seem to connect to my Nintendo Switch anymore. Sometimes it gives me random error codes, like "creeper" or "crossbow".

**Comment by G9-Dev** [comment] 2021-06-13 12:13
> idk if it's linked, but my Microsoft account doesn't seem to connect to my Nintendo Switch anymore. Sometimes it gives me random error codes, like "creeper" or "crossbow".

I solved it by login in from settings instead of main menu.

**Comment by IndigoAlkali** [comment] 2021-06-19 02:49
> There's a workaround:
> 
> 1. Enable local mode via the Y-button on the title screen.
> 2. Reenable online mode and wait until you logged into your Microsoft Account
> 3. Switch to the Server-Tab and choose any Server you like.
> 4. Wait until there's a number at Ping.
> 5. Connect and it should work now.

Currently having this issue but on Xbox One (Bedrock 1.17). I've repeatedly checked the primary and secondary DNS settings, tried the fix posted previously, and also ensured that the server I'm trying to join is online and working properly, all to no avail. I still get the "Unable to connect to world" issue.

**Comment by G9-Dev** [comment] 2021-06-19 17:53
They have updated Nintendo Switch Minecraft to 1.17.1, to fix this issue. Issue is now solved, but as Xbox One still doesn’t work, should I close issue ?

**Comment by Pugmatt** [comment] 2021-06-22 05:40
Since the original issue was for Switch, I say we can close it. If the issue appears to arrise again we can re-open. For Xbox we'll use the recent issue opened.

**Closed by Pugmatt** 2021-06-22 05:40 UTC
