### ISSUE TITLE
Stuck on connect to external server

### ISSUE THREAD

**Issue by lifegame1lu111** [Pugmatt/BedrockConnect#87] opened 2020-09-30 02:22 UTC
Hi, i am having trouble connect could you please give the dns a restart?
im on switch and its stuck on connect to external server

**Comment by Technoguyfication** [comment] 2020-12-22 21:49
Are you following this tutorial? https://www.youtube.com/watch?v=zalT_oR1nPM

**Comment by lifegame1lu111** [comment] 2021-03-08 20:43
yes its fixed already

**Comment by Technoguyfication** [comment] 2021-03-10 19:28
> yes its fixed already

Can you go ahead and close this issue if the issue is resolved please?

**Closed** 2022-02-04 19:12 UTC
