### ISSUE TITLE
Nintendo Switch Server list shows but not able to connect

### ISSUE THREAD

**Issue by zpsyx9** [Pugmatt/BedrockConnect#187] opened 2021-05-15 22:08 UTC
Was working flawlessly for months, suddenly stopped working. Thought it was my custom server at first, but found I'm unable to even connect to any of the official servers via the server list. Tried both U.S. based DNS servers. 

Troubleshooting steps taken with no success:
restarted switch
verified internet connection
Logged off MS account, logged back on
Loaded local world
Switched to different wifi connection (manually reentered DNS info) and repeated above steps
Restarted game several times

**Comment by Pugmatt** [comment] 2021-05-15 23:01
What happens when you connect, any errors?

Also just to confirm, the issue occurs on the featured server list on the Minecraft main menu, or when connected to the serverlist server and joining a server from there?

**Comment by CoolPeachGaming** [comment] 2021-09-19 07:04
Hello! I’m also having this problem.

When my friend connects, he gets the error: Enter a valid address.

I know the address is valid because I can join on my phone, and so can my other friends. It’s just this one friend playing on Switch.

This error occurs when on the serverlist server, and when joining a server from there.

Thank you!

**Comment by Pugmatt** [comment] 2021-09-22 01:46
> Hello! I’m also having this problem.
> 
> When my friend connects, he gets the error: Enter a valid address.
> 
> I know the address is valid because I can join on my phone, and so can my other friends. It’s just this one friend playing on Switch.
> 
> This error occurs when on the serverlist server, and when joining a server from there.
> 
> The first time he joined my personal server, it worked. This is only happening after I changed the IP and port.
> 
> Thank you!

The error would imply that the address is not a valid IP or domain, at least by what the server uses to check this when entered. Double-check that your friend isn't entering the port in the first input box, which can sometimes be a common mistake. 
If it's been confirmed it's not a mistype and everything's in the right box, would you be able to share the address that is being attempted to join, and/or possibly share a screenshot/picture of the game screen with the address entered into the form? (If prefered for privacy reasons, feel free to email these details to pugmatt(at)gmail.com instead of posting here) This way I can check to see if the address check on the BedrockConnect server is incorrectly marking it as an incorrect address.

**Closed** 2022-02-04 19:30 UTC
